// Code generated by bpf2go; DO NOT EDIT.
//go:build arm64be || armbe || mips || mips64 || mips64p32 || ppc64 || s390 || s390x || sparc || sparc64

package linux

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"

	"github.com/cilium/ebpf"
)

// loadBlocker returns the embedded CollectionSpec for blocker.
func loadBlocker() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_BlockerBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load blocker: %w", err)
	}

	return spec, err
}

// loadBlockerObjects loads blocker and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*blockerObjects
//	*blockerPrograms
//	*blockerMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadBlockerObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := loadBlocker()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// blockerSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type blockerSpecs struct {
	blockerProgramSpecs
	blockerMapSpecs
}

// blockerSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type blockerProgramSpecs struct {
	RestrictExec *ebpf.ProgramSpec `ebpf:"restrict_exec"`
}

// blockerMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type blockerMapSpecs struct {
	AllowedApps *ebpf.MapSpec `ebpf:"allowed_apps"`
}

// blockerObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadBlockerObjects or ebpf.CollectionSpec.LoadAndAssign.
type blockerObjects struct {
	blockerPrograms
	blockerMaps
}

func (o *blockerObjects) Close() error {
	return _BlockerClose(
		&o.blockerPrograms,
		&o.blockerMaps,
	)
}

// blockerMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadBlockerObjects or ebpf.CollectionSpec.LoadAndAssign.
type blockerMaps struct {
	AllowedApps *ebpf.Map `ebpf:"allowed_apps"`
}

func (m *blockerMaps) Close() error {
	return _BlockerClose(
		m.AllowedApps,
	)
}

// blockerPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadBlockerObjects or ebpf.CollectionSpec.LoadAndAssign.
type blockerPrograms struct {
	RestrictExec *ebpf.Program `ebpf:"restrict_exec"`
}

func (p *blockerPrograms) Close() error {
	return _BlockerClose(
		p.RestrictExec,
	)
}

func _BlockerClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed blocker_bpfeb.o
var _BlockerBytes []byte
